import sqlite3
import os

DB_PATH = os.path.join(os.path.dirname(__file__), 'tickets.db')

def migrate():
    print(f"Connecting to {DB_PATH}...")
    conn = sqlite3.connect(DB_PATH)
    cursor = conn.cursor()
    
    # Enable foreign keys
    cursor.execute("PRAGMA foreign_keys = ON")
    
    # Create projects table if not exists
    cursor.execute('''
    CREATE TABLE IF NOT EXISTS projects (
        id TEXT PRIMARY KEY,
        title TEXT NOT NULL,
        summary TEXT,
        documentation TEXT,
        status TEXT NOT NULL DEFAULT 'ACTIVE',
        owner TEXT,
        created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
        updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )
    ''')
    
    # Check if features table has project_id
    cursor.execute("PRAGMA table_info(features)")
    columns = [col[1] for col in cursor.fetchall()]
    
    if 'project_id' not in columns:
        print("Migrating features table to include project_id...")
        
        # Disable foreign keys temporarily for table rename/recreate
        cursor.execute("PRAGMA foreign_keys = OFF")
        
        # Insert default project
        cursor.execute('''
        INSERT OR IGNORE INTO projects (id, title, summary, documentation, owner)
        VALUES ('PRJ-DEFAULT', 'Default Project', 'Autogenerated default project for migration.', '', 'System')
        ''')
        
        # Create new table
        cursor.execute('''
        CREATE TABLE features_new (
            id TEXT PRIMARY KEY,
            title TEXT NOT NULL,
            summary TEXT,
            status TEXT NOT NULL DEFAULT 'ACTIVE',
            owner TEXT,
            project_id TEXT NOT NULL,
            created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
            updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY (project_id) REFERENCES projects(id)
        )
        ''')
        
        # Copy data
        cursor.execute('''
        INSERT INTO features_new (id, title, summary, status, owner, project_id, created_at, updated_at)
        SELECT id, title, summary, status, owner, 'PRJ-DEFAULT', created_at, updated_at
        FROM features
        ''')
        
        # Drop old table
        cursor.execute("DROP TABLE features")
        
        # Rename new table
        cursor.execute("ALTER TABLE features_new RENAME TO features")
        
        # Re-enable foreign keys
        cursor.execute("PRAGMA foreign_keys = ON")
        
        print("Migration complete!")
    else:
        print("Migration already applied.")

    conn.commit()
    conn.close()

if __name__ == "__main__":
    migrate()
